services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://luna_user:luna_password@db:5432/luna_db
      - OPENWEATHER_API_KEY=5ced3b5e72d491d8757816a2ef8aaf39 
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=luna_db
      - POSTGRES_USER=luna_user
      - POSTGRES_PASSWORD=luna_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U luna_user -d luna_db"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: