version: '3.8'

services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./luna_api:/app
    environment:
      - DATABASE_URL=postgresql://luna_user:luna_password@db/luna_db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=luna_db
      - POSTGRES_USER=luna_user
      - POSTGRES_PASSWORD=luna_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U luna_user -d luna_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

  # Reminder to self: Sets up API and DB services